### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку virt_mem_max Ялышева Наталья

### ISSUE THREAD

**Issue by rbbelka** [rbbelka/au-linux-kernel-spring-2016#4]
https://github.com/rbbelka/au-linux-kernel-spring-2016/commit/c283b38416989920c8e3bfc9d010c13369f50b05

**Comment by eabatalov** [comment]
Your implementation doesn't allocate the maximal amount of memory because you allocate each available size only once. Suppose we have 10 non-continuous pages available in address space. You'll allocate only one.

**Comment by eabatalov** [comment]
50 points out of 100.
